#!/usr/bin/env python3
"""Markdown ⇄ supplier-list converter — the curation pivot for supplier imports.

Same philosophy as `seed_csv.py`: MoM does NOT turn a messy source into triples in one
shot. A space's supplier list is free-form prose grown by successive `append` over years
— OpenFab's `fournisseurs.md` is French markdown with inconsistent formatting, dead
links, and businesses that closed. Parsing that straight into RDF bakes the rot in.

So the markdown always passes through a CSV a human reads:

    openfab.source.md  --to-csv-->  openfab.curation.csv
                                          |
                          (WebSearch curation + human review + geocoding)
                                          v
                        --to-ttl-->  openfab.ttl  --load_ontology.sh-->  Oxigraph

Two directions:

  to-csv   Extract suppliers from a space's markdown list into a curation CSV.
           Best-effort: it extracts what it can and WARNs about the rest. Nothing is
           dropped silently — an entry with no URL still gets a row.

  to-ttl   Convert a curated (and geocoded) CSV into Turtle, ready for
           `bash scripts/load_ontology.sh`.

Why plain Turtle and NOT a `GRAPH` block: the data belongs in a named graph, but the
graph is named by the LOAD URL (`PUT /store?graph=urn:mak:suppliers/<space>`), exactly
as mom.ttl and iop.ttl already are. Verified against Oxigraph 0.5.7:

  PUT  /store?graph=…  with TriG   → 400 "Named graphs are not allowed"
  POST /store          with TriG   → 204, but MERGES: a supplier deleted from the
                                     source would survive every future reload
  PUT  /store?graph=…  with Turtle → REPLACES that one graph, and only that one

So Turtle + graph-at-load-time is both the idempotent option and the one consistent
with the rest of the repo. (The VPS artifact this ports from shipped `.ttl` files
containing `GRAPH <…> { … }`, which is neither valid Turtle nor loadable at all.)

The member commentary (`comment`) is the irreplaceable value of these lists and is
carried verbatim end-to-end. Curation corrects verifiable facts; it never edits
judgement.

CSV columns (header row required; order free; unknown columns ignored):

  slug*       stable id → urn:mak:supplier/<slug>   REQUIRED (generated by to-csv)
  name*       schema:name                           REQUIRED
  category*   local name of a mom: category IRI     REQUIRED (e.g. "wood")
  comment     rdfs:comment @fr — member commentary, VERBATIM, never curated
  url         schema:url
  phone       schema:telephone
  email       schema:email
  street      schema:streetAddress
  postcode    schema:postalCode
  city        schema:addressLocality
  country     schema:addressCountry                 ISO 3166-1 alpha-2, default BE
  status      mom:operationalState (active | closed | unknown)
  death_reason        mom:deathReason (free text, when status=closed)
  operated_by          mom:operatedBy — slug of another row that is the same current
                        operator (see ontology/sup.ttl). Both rows stay; neither is deleted.
  verified_source_url where a curator confirmed the facts on this row
  verified_at         ISO date of that confirmation
  confidence          verified | unverified
  notes_curation      curator's own note — NOT member commentary, not ingested as comment
  lat / lon           decimal degrees (filled by geocode_suppliers.py)
  fidelity            mom:geolocationFidelity (exact | approximate | city)
  geo_note            mom:geolocationNote

Examples:
  python scripts/parse_suppliers.py to-csv \\
      --markdown data/supplier-lists/openfab.source.md \\
      --out data/supplier-lists/openfab.curation.csv \\
      --space openfab
  python scripts/parse_suppliers.py to-ttl \\
      --csv data/supplier-lists/openfab.curation.csv \\
      --out data/supplier-lists/openfab.ttl \\
      --space openfab \\
      --source-url https://raw.githubusercontent.com/openfab-lab/rtfm/refs/heads/master/faq/fournisseurs.md
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import logging
import re
import sys
from collections import Counter
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger("parse_suppliers")

COLUMNS = [
    "slug", "name", "category", "comment",
    "url", "phone", "email", "street", "postcode", "city", "country",
    "status", "death_reason", "operated_by",
    "verified_source_url", "verified_at", "confidence", "notes_curation",
    "lat", "lon", "fidelity", "geo_note",
]

# ── Category mapping ─────────────────────────────────────────────────────────
# Maps the French H2 section headers of the source markdown onto the ENGLISH local
# names of the shared mom: category IRIs (ontology/sup.ttl). English IRIs + trilingual
# labels is mom.ttl's existing convention (mom:ThreeDPrinting), and it is what lets a
# second space's list cross-reference this one instead of minting its own "bois".
CATEGORY_MAP = {
    "consommable d'entretient": "maintenance-consumables",
    "consommable d'entretien": "maintenance-consumables",
    "bois": "wood",
    "bois spéciaux": "specialty-wood",
    "plastique": "plastic",
    "metal": "metal",
    "métal": "metal",
    "mèches cnc": "cnc-bits",
    "visseries": "fasteners",
    "visserie": "fasteners",
    "electronics": "electronics",
    "électronique": "electronics",
    "electronique": "electronics",
    "textile": "textile",
    "cuir": "leather",
    "papier": "paper",
    "services": "services",
    "drinks": "drinks",
    "boissons": "drinks",
}

KNOWN_LOCALITIES = [
    "bruxelles", "brussel", "waterloo", "drogenbos", "laeken", "evere",
    "neder-over-heembeek", "jette", "anderlecht", "forest", "molenbeek",
    "namur", "nossegem", "zaventem", "walhain", "bever", "dilbeek",
    "heist-op-den-berg", "soumagne", "malmedy", "paris",
]


# ── Helpers ──────────────────────────────────────────────────────────────────

def slugify(name: str) -> str:
    s = name.lower().strip()
    s = (s.replace("é", "e").replace("è", "e").replace("ê", "e")
           .replace("à", "a").replace("â", "a").replace("ç", "c")
           .replace("ô", "o").replace("û", "u").replace("î", "i"))
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def category_for_header(header: str) -> str | None:
    key = header.strip().lower().rstrip(":").strip()
    if key in CATEGORY_MAP:
        return CATEGORY_MAP[key]
    for cat_key, local in CATEGORY_MAP.items():
        if cat_key in key or key in cat_key:
            return local
    return None


def clean_markdown_link(text: str) -> str:
    text = text.strip()
    m = re.match(r"\[([^\]]*)\]\(([^)]+)\)", text)
    if m:
        return m.group(2).strip()
    return text


def is_url(line: str) -> bool:
    line = line.strip().rstrip("\\")
    return line.startswith(("http://", "https://")) or bool(re.match(r"\[http", line))


def is_phone(line: str) -> bool:
    line = line.strip().rstrip("\\")
    if re.match(r"^[\+\(]?\d[\d\s/\-\.\(\)]{4,20}$", line):
        return True
    return bool(re.match(r"^(TEL|tel|tél)[:\s]", line))


def is_email(line: str) -> bool:
    line = line.strip().rstrip("\\")
    return "@" in line and "." in line.split("@")[-1] and " " not in line


def looks_like_address(line: str) -> bool:
    line = line.strip().rstrip("\\")
    if re.search(r"\b\d{4}\b", line):
        return True
    if any(k in line.lower() for k in KNOWN_LOCALITIES):
        return True
    if re.match(r"^\d+[,\s]", line):
        return True
    return bool(re.match(
        r"^(rue|chaussée|chaussee|quai|clos|place|avenue|boulevard|drève|dreve|zone)\s",
        line, flags=re.IGNORECASE))


def split_address(addr: str) -> tuple[str, str, str]:
    """Best-effort split into (street, postcode, city). Blanks are fine — curation fills them."""
    addr = addr.strip().rstrip("\\").strip()
    m = re.search(r"\b(\d{4})\b\s*,?\s*(.*)$", addr)
    if m:
        postcode = m.group(1)
        city = m.group(2).strip(" ,-")
        street = addr[:m.start()].strip(" ,-")
        return street, postcode, city
    for k in KNOWN_LOCALITIES:
        idx = addr.lower().rfind(k)
        if idx >= 0:
            return addr[:idx].strip(" ,-"), "", addr[idx:].strip(" ,-")
    return addr, "", ""


def clean_comment(lines: list[str]) -> str:
    parts = []
    for line in lines:
        s = line.strip().rstrip("\\").strip()
        s = re.sub(r"^>\s*", "", s)
        s = s.strip("_").strip()
        if s:
            parts.append(s)
    return " ".join(parts)


def escape_ttl(s: str) -> str:
    return (s.replace("\\", "\\\\").replace('"', '\\"')
             .replace("\n", "\\n").replace("\r", "\\r"))


# ── to-csv ───────────────────────────────────────────────────────────────────

def classify_line(line: str, cur: dict) -> None:
    raw = line.rstrip("\\").strip()
    if not raw or "![" in raw:
        return
    if raw.startswith(">") or (raw.startswith("_") and raw.endswith("_")):
        cur["comments"].append(raw)
        return
    if is_url(raw):
        url = clean_markdown_link(raw)
        if url not in cur["urls"]:
            cur["urls"].append(url)
        return
    if is_email(raw):
        if raw not in cur["emails"]:
            cur["emails"].append(raw)
        return
    if is_phone(raw):
        if raw not in cur["phones"]:
            cur["phones"].append(raw)
        return
    if looks_like_address(raw):
        if raw not in cur["addresses"]:
            cur["addresses"].append(raw)
        return
    if raw.lower().startswith("note") or raw.startswith("_"):
        cur["comments"].append(raw)
        return
    cur["other"].append(raw)


def parse_markdown(md: str, warn: Counter) -> list[dict]:
    suppliers: list[dict] = []
    category: str | None = None
    header_seen: set[str] = set()
    cur: dict | None = None

    def flush():
        nonlocal cur
        if cur and cur.get("name"):
            suppliers.append(cur)
        cur = None

    in_frontmatter = False
    for i, raw_line in enumerate(md.splitlines()):
        line = raw_line.strip()

        # YAML frontmatter at the very top only
        if i == 0 and line == "---":
            in_frontmatter = True
            continue
        if in_frontmatter:
            if line == "---":
                in_frontmatter = False
            continue

        if not line or "![" in line:
            continue

        if line.startswith("## ") and not line.startswith("###"):
            flush()
            header = line[3:].strip()
            header_seen.add(header)
            category = category_for_header(header)
            if category is None:
                warn["section_header_unmapped"] += 1
                log.warning(f"WARNING unmapped section header — entries under it get category='' : {header!r}")
            continue

        if line.startswith("### ") and not line.startswith("####"):
            # An H3 is a real sub-category only when it maps to a known concept
            # ("### Bois spéciaux" → specialty-wood). Otherwise it is an equipment
            # model or an editorial aside ("### autre?") and the parent category holds.
            flush()
            sub = category_for_header(line[4:].strip())
            if sub is not None and sub != category:
                header_seen.add(line[4:].strip())
                category = sub
            continue

        if line.startswith("#"):
            continue

        bold = re.match(r"\*\*([^*]+)\*\*[\s:]*", line)
        if bold:
            flush()
            name = bold.group(1).strip().rstrip(":").strip()
            cur = {"name": name, "category": category or "",
                   "urls": [], "phones": [], "emails": [],
                   "addresses": [], "comments": [], "other": []}
            rest = line[bold.end():].strip().rstrip("\\").strip()
            if rest:
                classify_line(rest, cur)
            continue

        if cur is None:
            continue
        classify_line(line, cur)

    flush()
    log.info(f"  sections seen: {len(header_seen)} → {sorted(header_seen)}")
    return suppliers


def to_csv(args) -> int:
    md_path = Path(args.markdown)
    if not md_path.exists():
        log.error(f"Markdown not found: {md_path}")
        return 1

    warn: Counter = Counter()
    suppliers = parse_markdown(md_path.read_text(encoding="utf-8"), warn)

    seen_slugs: dict[str, int] = {}
    rows = []
    for s in suppliers:
        slug = slugify(s["name"])
        if not slug:
            warn["name_unslugifiable"] += 1
            log.warning(f"WARNING name produces no slug, row skipped: {s['name']!r}")
            continue
        if slug in seen_slugs:
            seen_slugs[slug] += 1
            slug = f"{slug}-{seen_slugs[slug]}"
            warn["duplicate_name"] += 1
            log.warning(f"WARNING duplicate supplier name — disambiguated as {slug!r}: {s['name']!r}")
        else:
            seen_slugs[slug] = 1

        street = postcode = city = ""
        if s["addresses"]:
            street, postcode, city = split_address(s["addresses"][0])
            if len(s["addresses"]) > 1:
                warn["multiple_addresses"] += 1
                log.warning(f"WARNING {slug}: {len(s['addresses'])} address lines, kept the first — "
                            f"check notes_curation")

        if not s["urls"]:
            warn["missing_url"] += 1
        if not s["addresses"]:
            warn["missing_address"] += 1
        if not s["category"]:
            warn["missing_category"] += 1
        if not s["comments"]:
            warn["missing_comment"] += 1

        leftovers = "; ".join(s["other"])
        if leftovers:
            warn["unclassified_lines"] += 1

        rows.append({
            "slug": slug,
            "name": s["name"],
            "category": s["category"],
            "comment": clean_comment(s["comments"]),
            "url": s["urls"][0] if s["urls"] else "",
            "phone": s["phones"][0] if s["phones"] else "",
            "email": s["emails"][0] if s["emails"] else "",
            "street": street, "postcode": postcode, "city": city, "country": "BE",
            "status": "", "death_reason": "", "operated_by": "",
            "verified_source_url": "", "verified_at": "",
            "confidence": "unverified",
            "notes_curation": (f"extra urls: {'; '.join(s['urls'][1:])} " if len(s["urls"]) > 1 else "")
                              + (f"extra addresses: {'; '.join(s['addresses'][1:])} " if len(s["addresses"]) > 1 else "")
                              + (f"unclassified: {leftovers}" if leftovers else ""),
            "lat": "", "lon": "", "fidelity": "", "geo_note": "",
        })

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS)
        w.writeheader()
        w.writerows(rows)

    log.info(f"✓ wrote {len(rows)} suppliers → {out}")
    by_cat = Counter(r["category"] or "(none)" for r in rows)
    log.info(f"  categories: {len(by_cat)} → {dict(by_cat)}")
    if warn:
        log.info("  WARNING counters (nothing was dropped silently):")
        for k, v in sorted(warn.items()):
            log.info(f"    {k}: {v}")
    log.info("  Next: curate this CSV (WebSearch pass + human review), then "
             "python scripts/geocode_suppliers.py --csv <this>")
    return 0


# ── to-ttl ───────────────────────────────────────────────────────────────────

TTL_PREFIXES = """@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos:   <http://www.w3.org/2004/02/skos/core#> .
@prefix schema: <https://schema.org/> .
@prefix xsd:    <http://www.w3.org/2001/XMLSchema#> .
@prefix mom:    <https://nicolasdb.github.io/mapsofmaking_ontology/ns#> .
"""


def to_ttl(args) -> int:
    csv_path = Path(args.csv)
    if not csv_path.exists():
        log.error(f"CSV not found: {csv_path}")
        return 1

    space = args.space
    graph = f"urn:mak:suppliers/{space}"  # named at LOAD time, not in this file
    today = dt.date.today().isoformat()
    warn: Counter = Counter()

    with csv_path.open(encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))

    body: list[str] = []
    emitted = 0
    for r in rows:
        slug = (r.get("slug") or "").strip()
        name = (r.get("name") or "").strip()
        if not slug or not name:
            warn["row_missing_slug_or_name"] += 1
            log.warning(f"WARNING row missing slug or name, not emitted: {r!r}")
            continue

        t = [f'<urn:mak:supplier/{slug}> a mom:Supplier ;',
             f'    schema:name "{escape_ttl(name)}" ;']

        cat = (r.get("category") or "").strip()
        if cat:
            t.append(f"    mom:supplierCategory mom:supplier-{cat} ;")
        else:
            warn["no_category"] += 1

        for col, pred in (("url", "schema:url"),):
            v = (r.get(col) or "").strip()
            if v.startswith(("http://", "https://")):
                t.append(f"    {pred} <{v}> ;")
            elif v:
                warn["non_http_url"] += 1
                log.warning(f"WARNING {slug}: dropping non-http url {v!r}")

        for col, pred in (("phone", "schema:telephone"), ("email", "schema:email"),
                          ("street", "schema:streetAddress"), ("postcode", "schema:postalCode"),
                          ("city", "schema:addressLocality"),
                          ("country", "schema:addressCountry")):
            v = (r.get(col) or "").strip()
            if v:
                t.append(f'    {pred} "{escape_ttl(v)}" ;')

        comment = (r.get("comment") or "").strip()
        if comment:
            t.append(f'    rdfs:comment "{escape_ttl(comment)}"@fr ;')

        lat, lon = (r.get("lat") or "").strip(), (r.get("lon") or "").strip()
        fidelity = (r.get("fidelity") or "").strip()
        if lat and lon:
            if not fidelity:
                warn["coords_without_fidelity"] += 1
                log.warning(f"WARNING {slug}: coordinates without fidelity — not emitted "
                            f"(honesty about precision is required)")
            else:
                t.append(f'    schema:latitude "{lat}"^^xsd:decimal ;')
                t.append(f'    schema:longitude "{lon}"^^xsd:decimal ;')
                t.append(f'    mom:geolocationFidelity "{fidelity}" ;')
                geo_note = (r.get("geo_note") or "").strip()
                if geo_note:
                    t.append(f'    mom:geolocationNote "{escape_ttl(geo_note)}" ;')
        else:
            warn["no_coordinates"] += 1

        status = (r.get("status") or "").strip()
        if status:
            t.append(f'    mom:operationalState "{status}" ;')
        death_reason = (r.get("death_reason") or "").strip()
        if death_reason:
            t.append(f'    mom:deathReason "{escape_ttl(death_reason)}" ;')
        operated_by = (r.get("operated_by") or "").strip()
        if operated_by:
            t.append(f"    mom:operatedBy <urn:mak:supplier/{operated_by}> ;")
        verified_at = (r.get("verified_at") or "").strip()
        if verified_at:
            t.append(f'    mom:confirmedAt "{verified_at}"^^xsd:date ;')
        vsrc = (r.get("verified_source_url") or "").strip()
        if vsrc.startswith(("http://", "https://")):
            t.append(f"    mom:verifiedSource <{vsrc}> ;")
        elif (r.get("confidence") or "").strip() != "verified":
            warn["unverified"] += 1

        # Provenance, per entry — this is what will keep a Matrix-captured recommendation
        # distinguishable from a repo-curated one when that path lands.
        t.append(f"    mom:recommendedBy <urn:mak:space/{space}> ;")
        t.append(f"    mom:supplierListSource <{args.source_url}> ;")
        t.append(f'    schema:dateModified "{today}"^^xsd:date .')

        body.append("\n".join(t))
        emitted += 1

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    header = (
        f"# {space} suppliers — generated by scripts/parse_suppliers.py, do not hand-edit.\n"
        f"# Source:      {args.source_url}\n"
        f"# Curated CSV: {csv_path}\n"
        f"# Generated:   {today}\n"
        f"# Vocabulary:  ontology/sup.ttl (shared mom: terms — categories belong to no single space)\n"
        f"# Target graph: <{graph}> — named by the load URL, NOT by a GRAPH block here.\n"
        f"#   bash scripts/load_ontology.sh  →  PUT /store?graph={graph}\n"
        f"#   (Oxigraph rejects TriG on ?graph= with 400; PUT+Turtle replaces the graph,\n"
        f"#    which is what makes reloading idempotent.)\n\n"
    )
    out.write_text(header + TTL_PREFIXES + "\n" + "\n\n".join(body) + "\n", encoding="utf-8")

    log.info(f"✓ wrote {emitted} suppliers → {out}  (loads into graph <{graph}>)")
    if warn:
        log.info("  WARNING counters (nothing was dropped silently):")
        for k, v in sorted(warn.items()):
            log.info(f"    {k}: {v}")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description="Markdown ⇄ supplier-list converter")
    sub = p.add_subparsers(dest="cmd", required=True)

    p_tc = sub.add_parser("to-csv", help="Extract a markdown supplier list into a curation CSV")
    p_tc.add_argument("--markdown", required=True)
    p_tc.add_argument("--out", required=True)
    p_tc.add_argument("--space", required=True, help="Space slug the list belongs to (e.g. openfab)")
    p_tc.set_defaults(func=to_csv)

    p_tt = sub.add_parser("to-ttl", help="Convert a curated + geocoded CSV into Turtle")
    p_tt.add_argument("--csv", required=True)
    p_tt.add_argument("--out", required=True)
    p_tt.add_argument("--space", required=True)
    p_tt.add_argument("--source-url", required=True, help="Upstream URL of the original list")
    p_tt.set_defaults(func=to_ttl)

    args = p.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
